### ISSUE TITLE
QFN thermal pad

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#155]
The ATmega32U4 QFN thermal pad has a single via to transfer heat from the MCU to the bottom side. Should we add more vias?

![screen shot 2015-02-21 at 17 34 59](https://cloud.githubusercontent.com/assets/281642/6313599/08499be6-b9f0-11e4-9258-53aac0c1ed1d.png)

**Comment by Tsillen** [comment]
no need

**Comment by charlespax** [comment]
[citation needed]

**Comment by Tsillen** [comment]
You could add up all the loads and calculate the temperature rise etc... but that is a lot of work.
The TQFP version does not have any over heating issues as shown by arduino using that format on their products.

I see that you have a few IO and some busses etc. The current draw of the chip will be (very)low. In that case no extra "cooling" is needed. 

But if you really want add a few more via's to it. It won't do you any good as it might make the reflow process work less good due to the increased thermal resistance that the big bottom pad will have.,

**Comment by charlespax** [comment]
Cool. Let's leave things as they are. Moving to ice box.

**Comment by charlespax** [comment]
Will not do. Closing issue.
