### ISSUE TITLE
Battery reverse polarity protection

### ISSUE THREAD

**Issue by charlespax** [PaxInstruments/t400-electronics#166]
I would like to know if the T400 power system is protected against connecting a battery with reverse polarity. This is relevant to a situation where a user is hacking the device to run off an external power source via the battery connector or if they operate the device without an enclosure and use the wrong battery.

If USB power is connected, what happens if a battery is connected with reverse polarity?

If USB power is disconnected, what happens if a battery is connected with reverse polarity?

**Comment by samchoy88** [comment]
If USB power is connected, what happens if a battery is connected with reverse polarity?
If USB power is disconnected, what happens if a battery is connected with reverse polarity?

Both of the above case will result to short circuit. But short circuit only happen in MCP73831 battery charger. As MOSFET Q1 do not turn on and it becomes the barrier of the reverse current.

![image](https://cloud.githubusercontent.com/assets/1327611/7060489/619be288-deb4-11e4-95d9-9f8b69d7b23b.png)

**Comment by samchoy88** [comment]
I can add a P-MOSFET to prevent the battery polarity reversed. But it still contribute a little bit power lost and cost in circuit.
http://www.ti.com/lit/an/slva139/slva139.pdf

Besides, there is a protection circuit inside BL-5C battery.
See issue: Does the BL-5C have internal protection? #46

**Comment by charlespax** [comment]
We can keep things as they are as long as nothing is going to blow up.

**Comment by charlespax** [comment]
Closing issue.
